Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables.

In [2]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

In [9]:
## list: A list is a built-in data type in Python that can hold a collection of items of different data types.
# Lists are mutable, meaning you can add, remove, or modify elements after the list creation.

## Array_list :- lists, arrays are homogeneous, meaning they can only store elements of the same data type. 


print("Data type of list_ is :-", type(list_))

print("Data type of array_list is :-", type(array_list))



Data type of list_ is :- <class 'list'>
Data type of array_list is :- <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and 
arra_list.

In [ ]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

In [10]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [11]:
for j in array_list:
    print(type(j))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list

In [12]:
array_list = np.array(object = list_, dtype = int)

In [13]:
array_list

array([1, 2, 3, 4, 5])

In [14]:
# Here array_list variable is being redefined from string to int using the np.array() function with two arguments: object and dtype.

In [19]:
for i in list_:
    print(f"Data type of element '{i}': {type(i)}")

Data type of element '1': <class 'str'>
Data type of element '2': <class 'str'>
Data type of element '3': <class 'str'>
Data type of element '4': <class 'str'>
Data type of element '5': <class 'str'>


In [20]:
for i in array_list :
    print(f"Data type of element {i}: {type(i)}")

Data type of element 1: <class 'numpy.int64'>
Data type of element 2: <class 'numpy.int64'>
Data type of element 3: <class 'numpy.int64'>
Data type of element 4: <class 'numpy.int64'>
Data type of element 5: <class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [21]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [22]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
num_array.shape

(2, 3)

In [25]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [27]:
zero_matrix = np.zeros((3,3))

In [28]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.matrix(zero_matrix)

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [30]:
import numpy as np

identity_matrix = np.identity(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
